simplified the die-line when aclocal fails, the previous one confused the netbsd shell

diff --git a/buildconf b/buildconf
--- a/buildconf
+++ b/buildconf
@@ -159,7 +159,7 @@ fi
 echo "buildconf: running libtoolize"
 ${LIBTOOLIZE:-libtoolize} --copy --automake --force || die "The command '${LIBTOOLIZE:-libtoolize}  --copy --automake --force' failed"
 echo "buildconf: running aclocal"
-${ACLOCAL:-aclocal} $ACLOCAL_FLAGS || die "The command '${ACLOCAL:-aclocal}${ACLOCAL_FLAGS:+" $ACLOCAL_FLAGS"}' failed"
+${ACLOCAL:-aclocal} $ACLOCAL_FLAGS || die "The aclocal command line failed"
 echo "buildconf: running aclocal hack to convert all mv to mv -f"
 perl -i.bak -pe 's/\bmv +([^-\s])/mv -f $1/g' aclocal.m4
 echo "buildconf: running autoheader"
