oops, run libtoolize as the first tool

diff --git a/buildconf b/buildconf
--- a/buildconf
+++ b/buildconf
@@ -114,6 +114,8 @@ echo "buildconf: libtool version $lt_version (ok)"
 
 # run the correct scripts now
 
+echo "buildconf: running libtoolize"
+${LIBTOOLIZE:-libtoolize} --copy --automake || die "The command '${LIBTOOLIZE:-libtoolize}  --copy --automake' failed"
 echo "buildconf: running aclocal"
 ${ACLOCAL:-aclocal}       || die "The command '${AUTOHEADER:-aclocal}' failed"
 echo "buildconf: running autoheader"
@@ -122,7 +124,4 @@ echo "buildconf: running autoconf"
 ${AUTOCONF:-autoconf}     || die "The command '${AUTOCONF:-autoconf}' failed"
 echo "buildconf: running automake"
 ${AUTOMAKE:-automake} -a  || die "The command '${AUTOMAKE:-automake} -a' failed"
-echo "buildconf: running libtoolize"
-${LIBTOOLIZE:-libtoolize} --copy --automake || die "The command '${LIBTOOLIZE:-libtoolize}  --copy --automake' failed"
-
 exit 0
