- Andreas Farber made the 'buildconf' script check for the presence of m4   scripts to make it detect a bad checkout earlier. People with older   checkouts who don't do cvs update with the -d option won't get the new dirs   and then will get funny outputs that can be a bit hard to understand and   fix.

diff --git a/buildconf b/buildconf
--- a/buildconf
+++ b/buildconf
@@ -294,6 +294,11 @@ done
 echo "buildconf: running libtoolize"
 $libtoolize --copy --automake --force || die "The libtoolize command failed"
 
+if test ! -f m4/curl-functions.m4; then
+  echo "buildconf: cURL m4 macros not found"
+  exit 1
+fi
+
 echo "buildconf: running aclocal"
 ${ACLOCAL:-aclocal} -I m4 $ACLOCAL_FLAGS || die "The aclocal command line failed"
 
