Sterling Hughes's fixes

diff --git a/buildconf b/buildconf
--- a/buildconf
+++ b/buildconf
@@ -1,6 +1,11 @@
 #!/bin/sh
 
-automake Makefile
-aclocal
-autoheader
-autoconf
+die(){
+	echo "$@"
+	exit
+}
+
+automake Makefile || die "The command 'automake Makefile' failed"
+aclocal           || die "The command 'aclocal' failed"
+autoheader        || die "The command 'autoheader' failed"
+autoconf          || die "The command 'autoconf' failed"
