run libtoolize in the ares dir as well, and modified the output slightly for all tools run in the ares dir - now shown like "running ares/[tool]"

diff --git a/buildconf b/buildconf
--- a/buildconf
+++ b/buildconf
@@ -199,9 +199,11 @@ ${AUTOCONF:-autoconf}     || die "The autoconf command failed"
 
 if test -d ares; then
   cd ares
-  echo "buildconf: running aclocal in the ares directory"
+  echo "buildconf: running ares/libtoolize"
+${LIBTOOLIZE:-libtoolize} --copy --automake --force || die "The libtool command failed"
+  echo "buildconf: running ares/aclocal"
   ${ACLOCAL:-aclocal} $ACLOCAL_FLAGS || die "The ares aclocal command failed"
-  echo "buildconf: running autoconf in the ares directory"
+  echo "buildconf: running ares/autoconf"
   ${AUTOCONF:-autoconf}     || die "The ares autoconf command failed"
   cd ..
 fi
