run libtoolize too

diff --git a/buildconf b/buildconf
--- a/buildconf
+++ b/buildconf
@@ -122,5 +122,7 @@ echo "buildconf: running autoconf"
 ${AUTOCONF:-autoconf}     || die "The command '${AUTOCONF:-autoconf}' failed"
 echo "buildconf: running automake"
 ${AUTOMAKE:-automake} -a  || die "The command '${AUTOMAKE:-automake} -a' failed"
+echo "buildconf: running libtoolize"
+${LIBTOOLIZE:-libtoolize} --copy --automake || die "The command '${LIBTOOLIZE:-libtoolize}  --copy --automake' failed"
 
 exit 0
