retry dragonflybsd

diff --git a/.github/workflows/non-native.yml b/.github/workflows/non-native.yml
--- a/.github/workflows/non-native.yml
+++ b/.github/workflows/non-native.yml
@@ -86,8 +86,18 @@ jobs:
       - name: 'install prereqs'
         run: |
           if [ "${MATRIX_OS}" = 'dragonflybsd' ]; then
-            # https://github.com/DragonFlyBSD/DPorts
-            sudo pkg install -y autoconf automake libtool perl5 pkgconf brotli openldap26-client libidn2 libnghttp2
+            while [ $? = 0 ]; do
+              for i in 1 2 3; do
+                # https://github.com/DragonFlyBSD/DPorts
+                if sudo pkg install -y autoconf automake libtool perl5 pkgconf brotli openldap26-client libidn2 libnghttp2; then
+                  break 2
+                else
+                  echo "Error: wait to try again: $i"
+                  sleep 10
+                fi
+              done
+              false Too many retries
+            done
           elif [ "${MATRIX_OS}" = 'freebsd' ]; then
             # https://ports.freebsd.org/
             if [ "${MATRIX_BUILD}" = 'cmake' ]; then
